### ISSUE TITLE
The simulation results are inconsistent with the paper

### ISSUE THREAD

**Issue by wumaen** [akseljohan/Otter-USV-Target-Tracking-Controllers#5]
[error.pdf] (https://github.com/akseljohan/Otter-USV-Target-Tracking-Controllers/files/13944681/error.pdf)
Excuse me，The error in the simulation results of the MPC control method is close to 10，has the code been modified.

**Comment by akseljohan** [comment]
Hello, the NMPC performance depends on several factors such as values in the Q and R matrix, initial starting position and velocities of the the USV and the target. However, if you use the config and initial config that is documented in the result folder, then you should get similar results.

**Comment by wumaen** [comment]
> Hello, the NMPC performance depends on several factors such as values in the Q and R matrix, initial starting position and velocities of the the USV and the target. However, if you use the config and initial config that is documented in the result folder, then you should get similar results.
The problem has been resolved，thanks！
